# Generated by Django 3.2.8 on 2021-10-17 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='file',
        ),
    ]
